<?php
namespace App\Controllers\Admin;

use App\Controllers\BaseController;
use App\Models\TaskModel;
use App\Models\ProjectModel;
use App\Models\TaskCollaborationModel;
use App\Models\TaskAttachmentModel;
use App\Models\NotificationModel;
use App\Services\PmsAuthorizationService;

class TaskController extends BaseController
{
    protected $tm; protected $cm; protected $nm; protected $pmsAuth;
    public function __construct(){ $this->tm=new TaskModel(); $this->cm=new TaskCollaborationModel(); $this->nm=new NotificationModel(); $this->pmsAuth=new PmsAuthorizationService(); }
    private function canManageTask(int $projectId): bool { return $this->pmsAuth->canManageTask((string)session()->get('user_role'),(int)session()->get('user_id'),$projectId); }
    private function canAccessTask(array $task): bool { return $this->canManageTask((int)($task['project_id']??0)); }
    private function attachmentStorageRoot(): string { return rtrim(WRITEPATH, '/\\') . DIRECTORY_SEPARATOR . 'uploads' . DIRECTORY_SEPARATOR . 'task_attachments' . DIRECTORY_SEPARATOR; }
    public function index(){ $viewId=(int)$this->request->getGet('view'); if($viewId>0){$task=$this->tm->getWithDetails($viewId);if(!$task)return redirect()->to(base_url('admin/tasks'))->with('error','Task not found.');if(!$this->canAccessTask($task))return redirect()->to(base_url('admin/tasks'))->with('error','Access denied.');return view('admin/tasks/show',['title'=>'Task: '.$task['title'],'task'=>$task,'comments'=>$this->cm->comments($viewId),'subtasks'=>$this->cm->subtasks($viewId),'activities'=>$this->cm->activities($viewId),'attachments'=>(new TaskAttachmentModel())->forTask($viewId)]);} $filters=['project_id'=>$this->request->getGet('project_id'),'status'=>$this->request->getGet('status'),'priority'=>$this->request->getGet('priority'),'assigned_to'=>$this->request->getGet('assigned_to'),'search'=>$this->request->getGet('search')];$filters=array_filter($filters,static fn($v)=>$v!==null&&$v!=='');$visible=$this->pmsAuth->getVisibleProjectIds((string)session()->get('user_role'),(int)session()->get('user_id'));if($visible!==null&&empty($filters['project_id']))$filters['project_id_in']=$visible;$visibleProjects=$visible===null?(new ProjectModel())->select('id,name')->findAll():(new ProjectModel())->select('id,name')->whereIn('id',$visible?:[0])->findAll();return view('admin/tasks/index',['title'=>'Tasks','tasks'=>$this->tm->getAllWithDetails($filters),'projects'=>$visibleProjects,'statuses'=>TaskModel::STATUSES]); }
    public function kanban(){ $pid=(int)($this->request->getGet('project_id')?:0);if($pid>0&&!$this->canManageTask($pid))return redirect()->to(base_url('admin/tasks'))->with('error','Access denied.');$visible=$this->pmsAuth->getVisibleProjectIds((string)session()->get('user_role'),(int)session()->get('user_id'));$visibleProjects=$visible===null?(new ProjectModel())->select('id,name')->findAll():(new ProjectModel())->select('id,name')->whereIn('id',$visible?:[0])->findAll();$users=$this->db->table('users')->select('id,name')->orderBy('name','ASC')->get()->getResultArray();return view('admin/tasks/kanban',['title'=>'Kanban Board','columns'=>$this->tm->getKanbanBoard($pid?:null,$visible),'projects'=>$visibleProjects,'users'=>$users]); }
    public function uploadAttachment($id){$task=$this->tm->find((int)$id);if(!$task)return $this->jsonError('Task not found.');if(!$this->canAccessTask($task))return $this->jsonError('Access denied.');$file=$this->request->getFile('file');if(!$file||!$file->isValid())return $this->jsonError('Invalid file.');if(!$this->validate(['file'=>['rules'=>'uploaded[file]|max_size[file,10240]|ext_in[file,pdf,doc,docx,png,jpg,jpeg,gif,webp,xlsx,xls,csv,txt,zip]','errors'=>['ext_in'=>'File type not allowed.','max_size'=>'Max file size is 10MB.']]]))return $this->jsonError($this->validator->getError('file'));$originalName=$file->getClientName();$mimeType=$file->getClientMimeType();$size=$file->getSize();$isImage=in_array(strtolower($file->getClientExtension()),['png','jpg','jpeg','gif','webp'],true)?1:0;$newName=$file->getRandomName();$folder=$this->attachmentStorageRoot();if(!is_dir($folder)&&!mkdir($folder,0755,true)&&!is_dir($folder))return $this->jsonError('Unable to create secure attachment storage directory.');try{$file->move($folder,$newName);}catch(\Throwable $e){log_message('error','Task attachment upload failed: {message}',['message'=>$e->getMessage()]);return $this->jsonError('Unable to store the uploaded file.');}$attId=(new TaskAttachmentModel())->insert(['task_id'=>(int)$id,'filename'=>$newName,'original_name'=>$originalName,'mime_type'=>$mimeType,'size'=>$size,'is_image'=>$isImage,'uploaded_by'=>session()->get('user_id'),'created_at'=>date('Y-m-d H:i:s')]);if(!$attId){@unlink($folder.$newName);return $this->jsonError('Unable to save file information.');}$this->cm->log((int)$id,(int)session()->get('user_id'),'attachment_added',null,$originalName);return $this->jsonSuccess('File uploaded.',['id'=>$attId,'is_image'=>$isImage,'original_name'=>$originalName,'url'=>base_url('admin/tasks/attachments/'.$attId)]);}
    public function viewAttachment($attId){$att=(new TaskAttachmentModel())->find((int)$attId);if(!$att)return redirect()->back()->with('error','File not found.');$task=$this->tm->find((int)$att['task_id']);if(!$task||!$this->canAccessTask($task))return redirect()->back()->with('error','Access denied.');$path=$this->attachmentStorageRoot().$att['filename'];$root=realpath($this->attachmentStorageRoot());$real=realpath($path);if(!$root||!$real||!is_file($real)||!str_starts_with($real,$root.DIRECTORY_SEPARATOR))return redirect()->back()->with('error','File no longer exists on the server.');if(!empty($att['is_image']))return $this->response->setContentType($att['mime_type'])->setBody(file_get_contents($real));return $this->response->download($real,null)->setFileName($att['original_name']);}
    public function deleteAttachment($attId){$att=(new TaskAttachmentModel())->find((int)$attId);if(!$att)return $this->jsonError('File not found.');$task=$this->tm->find((int)$att['task_id']);if(!$task||!$this->canAccessTask($task))return $this->jsonError('Access denied.');$path=$this->attachmentStorageRoot().$att['filename'];if(is_file($path))@unlink($path);(new TaskAttachmentModel())->delete((int)$attId);$this->cm->log((int)$att['task_id'],(int)session()->get('user_id'),'attachment_removed',null,$att['original_name']);return $this->jsonSuccess('File removed.');}
    public function addComment($id){$task=$this->tm->getWithDetails((int)$id);if(!$task)return $this->jsonError('Task not found.');if(!$this->canAccessTask($task))return $this->jsonError('Access denied.');$body=trim((string)$this->request->getPost('body'));if($body==='')return $this->jsonError('Comment is required.');$userId=(int)session()->get('user_id');$this->cm->insert(['task_id'=>(int)$id,'user_id'=>$userId,'body'=>$body,'is_internal'=>1]);$this->cm->log((int)$id,$userId,'comment_added',null,$body);$this->notifyAssignee($task,'comment','New comment on task','A new comment was added to "'.$task['title'].'".',(int)$id,$userId);return $this->jsonSuccess('Comment added.');}
    public function addSubtask($id){$task=$this->tm->getWithDetails((int)$id);if(!$task)return $this->jsonError('Task not found.');if(!$this->canAccessTask($task))return $this->jsonError('Access denied.');$title=trim((string)$this->request->getPost('title'));if($title==='')return $this->jsonError('Subtask title is required.');$this->db->table('task_subtasks')->insert(['task_id'=>(int)$id,'title'=>$title,'is_completed'=>0,'created_by'=>session()->get('user_id'),'sort_order'=>0]);$this->cm->log((int)$id,(int)session()->get('user_id'),'subtask_added',null,$title);$this->notifyAssignee($task,'subtask','New subtask added','A subtask was added to "'.$task['title'].'".',(int)$id,(int)session()->get('user_id'));return $this->jsonSuccess('Subtask added.');}
    public function toggleSubtask($subtaskId){$row=$this->db->table('task_subtasks')->where('id',(int)$subtaskId)->get()->getRowArray();if(!$row)return $this->jsonError('Subtask not found.');$task=$this->tm->getWithDetails((int)$row['task_id']);if(!$task||!$this->canAccessTask($task))return $this->jsonError('Access denied.');$done=(int)!((int)$row['is_completed']);$this->db->table('task_subtasks')->where('id',(int)$subtaskId)->update(['is_completed'=>$done]);$this->cm->log((int)$row['task_id'],(int)session()->get('user_id'),'subtask_toggled',$row['is_completed'],$done);if($done)$this->notifyAssignee($task,'subtask_completed','Subtask completed','A subtask was completed for "'.$task['title'].'".',(int)$row['task_id'],(int)session()->get('user_id'));return $this->jsonSuccess('Subtask updated.',['completed'=>$done]);}
    public function store(){ $data=$this->request->getPost();unset($data['csrf_test_name']);$data['milestone_id']=!empty($data['milestone_id'])?(int)$data['milestone_id']:null;$data['project_id']=!empty($data['project_id'])?(int)$data['project_id']:null;if(!$data['project_id']||!$this->canManageTask((int)$data['project_id']))return $this->jsonError('Access denied.');$data['created_by']=session()->get('user_id');$data['status']=$this->normalizeStatus($data['status']??'todo');if(!$data['status'])return $this->jsonError('Invalid task status.');if(!in_array($data['priority']??'medium',['low','medium','high','urgent'],true))$data['priority']='medium';$data['is_issue']=!empty($data['is_issue'])?1:0;if(empty($data['title']))return $this->jsonError('Task title is required.');$id=$this->tm->insert($data);$task=$this->tm->getWithDetails((int)$id);$this->cm->log((int)$id,(int)session()->get('user_id'),'task_created',null,$data['title']);$this->notifyAssignee($task,'task_assigned','Task assigned','You have been assigned the task "'.$data['title'].'".',(int)$id,(int)session()->get('user_id'));return $this->jsonSuccess('Task created',['id'=>$id,'task'=>$task]); }
    public function update($id){$task=$this->tm->find((int)$id);if(!$task)return $this->jsonError('Task not found.');if(!$this->canAccessTask($task))return $this->jsonError('Access denied.');$data=$this->request->getPost();unset($data['csrf_test_name']);if(array_key_exists('milestone_id',$data))$data['milestone_id']=$data['milestone_id']?:null;if($this->request->getMethod()==='post'&&$this->request->getPost('_full_form')==='1')$data['is_issue']=!empty($data['is_issue'])?1:0;$newAssignee=array_key_exists('assigned_to',$data)?(int)$data['assigned_to']:0;if(array_key_exists('project_id',$data)&&$data['project_id']!=$task['project_id']&&!$this->canManageTask((int)$data['project_id']))return $this->jsonError('Access denied.');if(array_key_exists('status',$data)){$status=$this->normalizeStatus($data['status']);if(!$status)return $this->jsonError('Invalid task status.');$data['status']=$status;if($status==='done'&&empty($task['completed_date']))$data['completed_date']=date('Y-m-d');}$this->tm->update((int)$id,$data);$updated=$this->tm->getWithDetails((int)$id);$this->cm->log((int)$id,(int)session()->get('user_id'),'task_updated',null,$data);if($newAssignee>0&&$newAssignee!==(int)session()->get('user_id')&&$newAssignee!==(int)($task['assigned_to']??0))$this->nm->notify($newAssignee,'task_assigned','Task assigned','You have been assigned the task "'.$updated['title'].'".',(int)$id,'task');return $this->jsonSuccess('Task updated.');}
    public function updateStatus($id){$task=$this->tm->find((int)$id);if(!$task)return $this->jsonError('Task not found.');if(!$this->canAccessTask($task))return $this->jsonError('Access denied.');$status=$this->normalizeStatus((string)$this->request->getPost('status'));if(!$status)return $this->jsonError('Invalid task status.');$this->tm->update((int)$id,['status'=>$status,'completed_date'=>$status==='done'?date('Y-m-d'):null]);$this->cm->log((int)$id,(int)session()->get('user_id'),'status_changed',$task['status'],$status);$updated=$this->tm->getWithDetails((int)$id);$this->notifyAssignee($updated,'task_status','Task status changed','"'.$updated['title'].'" moved to '.ucwords(str_replace('_',' ',$status)).'.',(int)$id,(int)session()->get('user_id'));return $this->jsonSuccess('Status updated.',['status'=>$status]);}
    public function reorder(){$status=$this->normalizeStatus((string)$this->request->getPost('status'));$ids=$this->request->getPost('ids');if(!$status||!is_array($ids))return $this->jsonError('Invalid Kanban ordering request.');foreach(array_values($ids)as$position=>$id){$task=$this->tm->find((int)$id);if(!$task||!$this->canAccessTask($task))return $this->jsonError('Access denied.');$oldStatus=$task['status'];$this->tm->update((int)$id,['status'=>$status,'sort_order'=>$position,'completed_date'=>$status==='done'?date('Y-m-d'):null]);if($oldStatus!==$status){$this->cm->log((int)$id,(int)session()->get('user_id'),'status_changed',$oldStatus,$status);$updated=$this->tm->getWithDetails((int)$id);$this->notifyAssignee($updated,'task_status','Task status changed','"'.$updated['title'].'" moved to '.ucwords(str_replace('_',' ',$status)).'.',(int)$id,(int)session()->get('user_id'));}}if(!empty($ids))$this->cm->log((int)$ids[0],(int)session()->get('user_id'),'kanban_reordered',null,['status'=>$status,'count'=>count($ids)]);return $this->jsonSuccess('Kanban order saved.');}
    public function delete($id){$task=$this->tm->find((int)$id);if(!$task)return $this->jsonError('Task not found.');if(!$this->canManageTask((int)$task['project_id']))return $this->jsonError('Access denied.');$this->cm->log((int)$id,(int)session()->get('user_id'),'task_deleted',null,$task['title']);$this->tm->delete((int)$id);return $this->jsonSuccess('Deleted');}
    private function notifyAssignee(?array $task,string $type,string $title,string $message,int $referenceId,int $actorId):void{if(!$task)return;$assignee=(int)($task['assigned_to']??0);if($assignee>0&&$assignee!==$actorId)$this->nm->notify($assignee,$type,$title,$message,$referenceId,'task');}
    private function normalizeStatus(string $status):?string{$status=strtolower(trim($status));$status=['review'=>'code_review','completed'=>'done','hold'=>'blocked'][$status]??$status;return in_array($status,TaskModel::STATUSES,true)?$status:null;}
}
