<?php
namespace App\Controllers\Admin;

use App\Controllers\BaseController;
use App\Models\TaskModel;
use App\Models\ProjectModel;
use App\Models\TaskCollaborationModel;

class TaskController extends BaseController
{
    protected $tm; protected $cm;
    public function __construct(){ $this->tm=new TaskModel(); $this->cm=new TaskCollaborationModel(); }
    public function index(){
        $viewId=(int)$this->request->getGet('view');
        if($viewId>0){ $task=$this->tm->getWithDetails($viewId); if(!$task)return redirect()->to(base_url('admin/tasks'))->with('error','Task not found.'); return view('admin/tasks/show',['title'=>'Task: '.$task['title'],'task'=>$task,'comments'=>$this->cm->comments($viewId),'subtasks'=>$this->cm->subtasks($viewId),'activities'=>$this->cm->activities($viewId)]); }
        $filters=['project_id'=>$this->request->getGet('project_id'),'status'=>$this->request->getGet('status'),'priority'=>$this->request->getGet('priority'),'assigned_to'=>$this->request->getGet('assigned_to'),'search'=>$this->request->getGet('search')]; $filters=array_filter($filters,static fn($v)=>$v!==null&&$v!=='');
        return view('admin/tasks/index',['title'=>'Tasks','tasks'=>$this->tm->getAllWithDetails($filters),'projects'=>(new ProjectModel())->select('id,name')->findAll(),'statuses'=>TaskModel::STATUSES]);
    }
    public function kanban(){ $pid=(int)($this->request->getGet('project_id')?:0); return view('admin/tasks/kanban',['title'=>'Kanban Board','columns'=>$this->tm->getKanbanBoard($pid?:null),'projects'=>(new ProjectModel())->select('id,name')->findAll()]); }
    public function addComment($id){if(!$this->tm->find((int)$id))return $this->jsonError('Task not found.');$body=trim((string)$this->request->getPost('body'));if($body==='')return $this->jsonError('Comment is required.');$this->cm->insert(['task_id'=>(int)$id,'user_id'=>session()->get('user_id'),'body'=>$body,'is_internal'=>1]);$this->cm->log((int)$id,(int)session()->get('user_id'),'comment_added',null,$body);return $this->jsonSuccess('Comment added.');}
    public function addSubtask($id){if(!$this->tm->find((int)$id))return $this->jsonError('Task not found.');$title=trim((string)$this->request->getPost('title'));if($title==='')return $this->jsonError('Subtask title is required.');$this->db->table('task_subtasks')->insert(['task_id'=>(int)$id,'title'=>$title,'is_completed'=>0,'created_by'=>session()->get('user_id'),'sort_order'=>0]);$this->cm->log((int)$id,(int)session()->get('user_id'),'subtask_added',null,$title);return $this->jsonSuccess('Subtask added.');}
    public function toggleSubtask($subtaskId){$row=$this->db->table('task_subtasks')->where('id',(int)$subtaskId)->get()->getRowArray();if(!$row)return $this->jsonError('Subtask not found.');$done=(int)!((int)$row['is_completed']);$this->db->table('task_subtasks')->where('id',(int)$subtaskId)->update(['is_completed'=>$done]);$this->cm->log((int)$row['task_id'],(int)session()->get('user_id'),'subtask_toggled',$row['is_completed'],$done);return $this->jsonSuccess('Subtask updated.',['completed'=>$done]);}
    public function store(){ $data=$this->request->getPost();unset($data['csrf_test_name']);$data['milestone_id']=!empty($data['milestone_id'])?(int)$data['milestone_id']:null;$data['project_id']=!empty($data['project_id'])?(int)$data['project_id']:null;$data['created_by']=session()->get('user_id');$data['status']=$this->normalizeStatus($data['status']??'todo');if(!$data['status'])return $this->jsonError('Invalid task status.');if(!in_array($data['priority']??'medium',['low','medium','high','urgent'],true))$data['priority']='medium';if(empty($data['title']))return $this->jsonError('Task title is required.');$id=$this->tm->insert($data);$this->cm->log((int)$id,(int)session()->get('user_id'),'task_created',null,$data['title']);return $this->jsonSuccess('Task created',['id'=>$id,'task'=>$this->tm->getWithDetails((int)$id)]); }
    public function update($id){$task=$this->tm->find((int)$id);if(!$task)return $this->jsonError('Task not found.');$data=$this->request->getPost();unset($data['csrf_test_name']);if(array_key_exists('milestone_id',$data))$data['milestone_id']=$data['milestone_id']?:null;if(array_key_exists('status',$data)){$status=$this->normalizeStatus($data['status']);if(!$status)return $this->jsonError('Invalid task status.');$data['status']=$status;if($status==='done'&&empty($task['completed_date']))$data['completed_date']=date('Y-m-d');}$this->tm->update((int)$id,$data);$this->cm->log((int)$id,(int)session()->get('user_id'),'task_updated',null,$data);return $this->jsonSuccess('Task updated.');}
    public function updateStatus($id){$task=$this->tm->find((int)$id);if(!$task)return $this->jsonError('Task not found.');$status=$this->normalizeStatus((string)$this->request->getPost('status'));if(!$status)return $this->jsonError('Invalid task status.');$this->tm->update((int)$id,['status'=>$status,'completed_date'=>$status==='done'?date('Y-m-d'):null]);$this->cm->log((int)$id,(int)session()->get('user_id'),'status_changed',$task['status'],$status);return $this->jsonSuccess('Status updated.',['status'=>$status]);}
    public function reorder(){$status=$this->normalizeStatus((string)$this->request->getPost('status'));$ids=$this->request->getPost('ids');if(!$status||!is_array($ids))return $this->jsonError('Invalid Kanban ordering request.');foreach(array_values($ids)as$position=>$id){$task=$this->tm->find((int)$id);if(!$task)continue;$oldStatus=$task['status'];$this->tm->update((int)$id,['status'=>$status,'sort_order'=>$position,'completed_date'=>$status==='done'?date('Y-m-d'):null]);if($oldStatus!==$status)$this->cm->log((int)$id,(int)session()->get('user_id'),'status_changed',$oldStatus,$status);}$this->cm->log((int)$ids[0],(int)session()->get('user_id'),'kanban_reordered',null,['status'=>$status,'count'=>count($ids)]);return $this->jsonSuccess('Kanban order saved.');}
    public function delete($id){$task=$this->tm->find((int)$id);if(!$task)return $this->jsonError('Task not found.');$this->cm->log((int)$id,(int)session()->get('user_id'),'task_deleted',null,$task['title']);$this->tm->delete((int)$id);return $this->jsonSuccess('Deleted');}
    private function normalizeStatus(string $status):?string{$status=strtolower(trim($status));$status=['review'=>'code_review','completed'=>'done','hold'=>'blocked'][$status]??$status;return in_array($status,TaskModel::STATUSES,true)?$status:null;}
}
