<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<style>
.kanban-toolbar{background:linear-gradient(135deg,#ffffff 0%,#f8fafc 100%);border:1px solid #e9ecef;border-radius:16px;padding:14px 16px;box-shadow:0 4px 18px rgba(15,23,42,.05)}
.kanban-board{gap:16px!important;padding:4px 4px 18px;scrollbar-width:thin}
.kanban-column{min-width:270px;max-width:300px;background:#f8fafc;border:1px solid #e9ecef!important;border-radius:16px!important;overflow:hidden;box-shadow:0 5px 20px rgba(15,23,42,.05)}
.kanban-column-header{padding:13px 14px;border-bottom:1px solid #e9ecef;background:#fff}
.kanban-column.todo .kanban-column-header{border-top:4px solid #64748b}.kanban-column.in_progress .kanban-column-header{border-top:4px solid #3b82f6}.kanban-column.code_review .kanban-column-header{border-top:4px solid #06b6d4}.kanban-column.qa .kanban-column-header{border-top:4px solid #f59e0b}.kanban-column.client_review .kanban-column-header{border-top:4px solid #8b5cf6}.kanban-column.blocked .kanban-column-header{border-top:4px solid #ef4444}.kanban-column.done .kanban-column-header{border-top:4px solid #22c55e}.kanban-column.cancelled .kanban-column-header{border-top:4px solid #334155}
.kanban-col{min-height:400px;padding:10px!important}
.kanban-card{border:1px solid #e9ecef!important;border-radius:13px!important;background:#fff;transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease;cursor:grab;overflow:hidden}
.kanban-card:hover{transform:translateY(-2px);box-shadow:0 9px 24px rgba(15,23,42,.10)!important;border-color:#cbd5e1!important}.kanban-card:active{cursor:grabbing}
.kanban-card .card-head{padding:11px 12px 8px;border-bottom:1px solid #f1f3f5}.kanban-card .card-body-content{padding:11px 12px}.kanban-card .card-foot{padding:8px 12px;border-top:1px solid #f1f3f5;background:#fafafa}
.priority-pill{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.4px;padding:4px 7px;border-radius:999px}.priority-low{background:#dcfce7;color:#166534}.priority-medium{background:#fef3c7;color:#92400e}.priority-high{background:#fee2e2;color:#b91c1c}.priority-urgent{background:#7f1d1d;color:#fff}
.task-meta{font-size:11px;color:#64748b;display:flex;align-items:center;gap:5px;margin-top:5px}.task-title{font-size:13px;line-height:1.35;font-weight:650;color:#1e293b}.task-description{font-size:11px;color:#64748b;line-height:1.4;margin-top:6px}.task-due{font-size:11px}.kanban-empty{border:1px dashed #cbd5e1;border-radius:12px;padding:28px 10px;text-align:center;color:#94a3b8;font-size:11px;background:rgba(255,255,255,.55)}
</style>
<div class="kanban-toolbar d-flex justify-content-between mb-3 flex-wrap gap-2"><div class="d-flex gap-2 align-items-center"><select id="projectFilter" class="form-select form-select-sm" style="width:220px" onchange="location.href='?project_id='+this.value"><option value="">All Projects</option><?php foreach($projects as $p): ?><option value="<?= $p['id'] ?>" <?= (int)($_GET['project_id'] ?? 0)===(int)$p['id']?'selected':'' ?>><?= esc($p['name']) ?></option><?php endforeach; ?></select></div><div class="d-flex gap-2"><a href="<?= base_url('admin/tasks') ?>" class="btn btn-outline-secondary btn-sm"><i class="bi bi-list-task me-1"></i>List View</a><button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#addTaskModal"><i class="bi bi-plus-lg me-1"></i>Add Task</button></div></div>
<div class="d-flex flex-nowrap overflow-auto pb-3 kanban-board" id="kanbanBoard" style="min-height:70vh">
<?php $colConfig=['todo'=>['label'=>'To Do','color'=>'secondary','icon'=>'bi-circle'],'in_progress'=>['label'=>'In Progress','color'=>'primary','icon'=>'bi-arrow-clockwise'],'code_review'=>['label'=>'Code Review','color'=>'info','icon'=>'bi-search'],'qa'=>['label'=>'QA','color'=>'warning','icon'=>'bi-bug'],'client_review'=>['label'=>'Client Review','color'=>'primary','icon'=>'bi-person-check'],'blocked'=>['label'=>'Blocked','color'=>'danger','icon'=>'bi-pause-circle'],'done'=>['label'=>'Done','color'=>'success','icon'=>'bi-check-circle'],'cancelled'=>['label'=>'Cancelled','color'=>'dark','icon'=>'bi-x-circle']]; foreach($columns as $status=>$tasks): $cfg=$colConfig[$status]??['label'=>ucfirst($status),'color'=>'secondary','icon'=>'bi-circle']; ?>
<div class="kanban-column <?= esc($status) ?> flex-shrink-0"><div class="kanban-column-header"><div class="d-flex align-items-center gap-2"><i class="bi <?= $cfg['icon'] ?> text-<?= $cfg['color'] ?>"></i><span class="fw-semibold small"><?= $cfg['label'] ?></span><span class="badge bg-<?= $cfg['color'] ?> ms-auto rounded-pill"><?= count($tasks) ?></span></div></div><div class="kanban-col" data-status="<?= $status ?>">
<?php if(empty($tasks)): ?><div class="kanban-empty"><i class="bi bi-inbox fs-5 d-block mb-1"></i>No tasks here</div><?php endif; ?>
<?php foreach($tasks as $task): $priority=$task['priority']??'medium'; $ov=!empty($task['due_date'])&&$task['due_date']!=='0000-00-00'&&strtotime($task['due_date'])<time()&&$status!=='done'&&$status!=='cancelled'; ?>
<div class="card kanban-card mb-2" data-id="<?= $task['id'] ?>" draggable="true"><div class="card-head"><div class="d-flex justify-content-between align-items-start gap-2"><span class="priority-pill priority-<?= esc($priority) ?>"><?= ucfirst($priority) ?></span><button class="btn btn-xs text-muted btn-del-task p-0" data-id="<?= $task['id'] ?>" data-confirm-title="Delete Task?" data-confirm="Delete '<?= esc($task['title']) ?>'?" data-confirm-yes="Yes, Delete"><i class="bi bi-three-dots-vertical"></i></button></div></div><div class="card-body-content"><div class="task-title"><?= esc($task['title']) ?></div><?php if(!empty($task['description'])): ?><div class="task-description"><?= esc(mb_strimwidth(strip_tags($task['description']),0,110,'…')) ?></div><?php endif; ?><?php if($task['project_name']??null): ?><div class="task-meta"><i class="bi bi-folder2"></i><?= esc($task['project_name']) ?></div><?php endif; ?><?php if($task['milestone_title']??null): ?><div class="task-meta"><i class="bi bi-flag"></i><?= esc($task['milestone_title']) ?></div><?php endif; ?><?php if($task['assigned_name']??null): ?><div class="task-meta"><i class="bi bi-person-circle"></i><?= esc($task['assigned_name']) ?></div><?php endif; ?></div><div class="card-foot d-flex justify-content-between align-items-center"><span class="task-due <?= $ov?'text-danger fw-semibold':'text-muted' ?>"><?php if(!empty($task['due_date'])&&$task['due_date']!=='0000-00-00'): ?><i class="bi bi-calendar3 me-1"></i><?= date('d M',strtotime($task['due_date'])) ?><?= $ov?' ⚠':'' ?><?php else: ?><span class="text-muted">No due date</span><?php endif; ?></span><span class="text-muted" style="font-size:10px"><i class="bi bi-grip-vertical"></i></span></div></div>
<?php endforeach; ?></div></div>
<?php endforeach; ?></div>
<div class="modal fade" id="addTaskModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><div class="modal-header border-0"><h5 class="modal-title fw-semibold">Add Task</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><form id="addTaskForm"><?= csrf_field() ?><div class="modal-body row g-3"><div class="col-12"><label class="form-label small fw-semibold">Project *</label><select name="project_id" class="form-select" required><option value="">Select Project</option><?php foreach($projects as $p): ?><option value="<?= $p['id'] ?>"><?= esc($p['name']) ?></option><?php endforeach; ?></select></div><div class="col-12"><label class="form-label small fw-semibold">Title *</label><input type="text" name="title" class="form-control" required></div><div class="col-12"><label class="form-label small fw-semibold">Description</label><textarea name="description" class="form-control" rows="2"></textarea></div><div class="col-md-6"><label class="form-label small fw-semibold">Priority</label><select name="priority" class="form-select"><option value="low">Low</option><option value="medium" selected>Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></div><div class="col-md-6"><label class="form-label small fw-semibold">Due Date</label><input type="date" name="due_date" class="form-control"></div><div class="col-12"><label class="form-label small fw-semibold">Initial Status</label><select name="status" class="form-select"><option value="todo" selected>To Do</option><option value="in_progress">In Progress</option><option value="code_review">Code Review</option><option value="qa">QA</option><option value="client_review">Client Review</option><option value="blocked">Blocked</option></select></div></div><div class="modal-footer border-0"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary">Add Task</button></div></form></div></div></div>
<?= $this->endSection() ?>
<?= $this->section('scripts') ?>
<script>
const BASE='<?= base_url() ?>';
$('#addTaskForm').on('submit',function(e){e.preventDefault();showLoader('Adding...');$.post(`${BASE}admin/tasks/store`,$(this).serialize(),res=>{hideLoader();showToast(res.message,res.status);if(res.status==='success'){bootstrap.Modal.getInstance(document.getElementById('addTaskModal')).hide();setTimeout(()=>location.reload(),500)}},'json')});
let dragged=null;document.querySelectorAll('.kanban-card').forEach(card=>{card.addEventListener('dragstart',()=>{dragged=card;card.classList.add('opacity-50')});card.addEventListener('dragend',()=>{card.classList.remove('opacity-50');dragged=null})});document.querySelectorAll('.kanban-col').forEach(col=>{col.addEventListener('dragover',e=>{e.preventDefault();if(dragged&&dragged.parentElement!==col)col.appendChild(dragged)});col.addEventListener('drop',e=>{e.preventDefault();if(!dragged)return;const status=col.dataset.status;showLoader('Saving...');$.post(`${BASE}admin/tasks/reorder`,{status:status,ids:Array.from(col.querySelectorAll('.kanban-card')).map(x=>x.dataset.id),csrf_test_name:getCsrfToken()},res=>{hideLoader();showToast(res.message,res.status)},'json')})});
let delId=null;$(document).on('click','.btn-del-task',function(){delId=$(this).data('id');$('#ngConfirmTitle').text($(this).data('confirm-title'));$('#ngConfirmMessage').text($(this).data('confirm'));$('#ngConfirmYes').text($(this).data('confirm-yes'));bootstrap.Modal.getOrCreateInstance(document.getElementById('ngConfirmModal')).show()});$('#ngConfirmYes').off('click').on('click',function(){if(!delId)return;bootstrap.Modal.getInstance(document.getElementById('ngConfirmModal')).hide();showLoader('Deleting...');$.post(`${BASE}admin/tasks/delete/${delId}`,{csrf_test_name:getCsrfToken()},res=>{hideLoader();showToast(res.message,res.status);if(res.status==='success')setTimeout(()=>location.reload(),400)},'json');delId=null});
</script>
<?= $this->endSection() ?>