<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<div class="d-flex justify-content-between mb-3 flex-wrap gap-2"><div class="d-flex gap-2 align-items-center"><select id="projectFilter" class="form-select form-select-sm" style="width:220px" onchange="location.href='?project_id='+this.value"><option value="">All Projects</option><?php foreach ($projects as $p): ?><option value="<?= $p['id'] ?>" <?= (int)($_GET['project_id'] ?? 0)===(int)$p['id']?'selected':'' ?>><?= esc($p['name']) ?></option><?php endforeach; ?></select></div><div class="d-flex gap-2"><a href="<?= base_url('admin/tasks') ?>" class="btn btn-outline-secondary btn-sm"><i class="bi bi-list-task me-1"></i>List View</a><button class="btn btn-primary btn-sm" data-bs-toggle="modal" data-bs-target="#addTaskModal"><i class="bi bi-plus-lg me-1"></i>Add Task</button></div></div>
<div class="row g-3 flex-nowrap overflow-auto pb-3" id="kanbanBoard" style="min-height:70vh">
<?php $colConfig=['todo'=>['label'=>'To Do','color'=>'secondary','icon'=>'bi-circle'],'in_progress'=>['label'=>'In Progress','color'=>'primary','icon'=>'bi-arrow-clockwise'],'code_review'=>['label'=>'Code Review','color'=>'info','icon'=>'bi-search'],'qa'=>['label'=>'QA','color'=>'warning','icon'=>'bi-bug'],'client_review'=>['label'=>'Client Review','color'=>'primary','icon'=>'bi-person-check'],'blocked'=>['label'=>'Blocked','color'=>'danger','icon'=>'bi-pause-circle'],'done'=>['label'=>'Done','color'=>'success','icon'=>'bi-check-circle'],'cancelled'=>['label'=>'Cancelled','color'=>'dark','icon'=>'bi-x-circle']]; foreach($columns as $status=>$tasks): $cfg=$colConfig[$status]??['label'=>ucfirst($status),'color'=>'secondary','icon'=>'bi-circle']; ?>
<div class="col" style="min-width:240px;max-width:280px"><div class="card border-0 h-100" style="background:#f8f9fb"><div class="card-header border-0 py-2 px-3 bg-transparent"><div class="d-flex align-items-center gap-2"><i class="bi <?= $cfg['icon'] ?> text-<?= $cfg['color'] ?>"></i><span class="fw-semibold small"><?= $cfg['label'] ?></span><span class="badge bg-<?= $cfg['color'] ?> ms-auto"><?= count($tasks) ?></span></div></div><div class="card-body px-2 py-1 kanban-col" data-status="<?= $status ?>" style="min-height:400px">
<?php foreach($tasks as $task): $pc=['low'=>'success','medium'=>'warning','high'=>'danger','urgent'=>'danger'][$task['priority']??'medium']??'secondary'; $ov=!empty($task['due_date'])&&$task['due_date']!=='0000-00-00'&&strtotime($task['due_date'])<time()&&$status!=='done'&&$status!=='cancelled'; ?>
<div class="card border-0 shadow-sm mb-2 kanban-card" data-id="<?= $task['id'] ?>" draggable="true"><div class="card-body p-3"><div class="d-flex justify-content-between align-items-start mb-1"><span class="badge bg-<?= $pc ?> badge-sm"><?= ucfirst($task['priority']??'medium') ?></span><button class="btn btn-xs text-muted btn-del-task p-0" data-id="<?= $task['id'] ?>" data-confirm-title="Delete Task?" data-confirm="Delete '<?= esc($task['title']) ?>'?" data-confirm-yes="Yes, Delete"><i class="bi bi-x"></i></button></div><div class="fw-semibold small mb-1"><?= esc($task['title']) ?></div><?php if($task['project_name']??null): ?><div class="text-muted" style="font-size:11px"><i class="bi bi-folder2 me-1"></i><?= esc($task['project_name']) ?></div><?php endif; ?><?php if($task['milestone_title']??null): ?><div class="text-muted" style="font-size:11px"><i class="bi bi-flag me-1"></i><?= esc($task['milestone_title']) ?></div><?php endif; ?><?php if($task['assigned_name']??null): ?><div class="text-muted" style="font-size:11px"><i class="bi bi-person me-1"></i><?= esc($task['assigned_name']) ?></div><?php endif; ?><?php if(!empty($task['due_date'])&&$task['due_date']!=='0000-00-00'): ?><div class="mt-1 <?= $ov?'text-danger':'text-muted' ?>" style="font-size:11px"><i class="bi bi-calendar me-1"></i><?= date('d M',strtotime($task['due_date'])) ?><?= $ov?' ⚠':'' ?></div><?php endif; ?></div></div>
<?php endforeach; ?></div></div></div>
<?php endforeach; ?></div>
<div class="modal fade" id="addTaskModal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><div class="modal-header border-0"><h5 class="modal-title fw-semibold">Add Task</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><form id="addTaskForm"><?= csrf_field() ?><div class="modal-body row g-3"><div class="col-12"><label class="form-label small fw-semibold">Project *</label><select name="project_id" class="form-select" required><option value="">Select Project</option><?php foreach($projects as $p): ?><option value="<?= $p['id'] ?>"><?= esc($p['name']) ?></option><?php endforeach; ?></select></div><div class="col-12"><label class="form-label small fw-semibold">Title *</label><input type="text" name="title" class="form-control" required></div><div class="col-12"><label class="form-label small fw-semibold">Description</label><textarea name="description" class="form-control" rows="2"></textarea></div><div class="col-md-6"><label class="form-label small fw-semibold">Priority</label><select name="priority" class="form-select"><option value="low">Low</option><option value="medium" selected>Medium</option><option value="high">High</option><option value="urgent">Urgent</option></select></div><div class="col-md-6"><label class="form-label small fw-semibold">Due Date</label><input type="date" name="due_date" class="form-control"></div><div class="col-12"><label class="form-label small fw-semibold">Initial Status</label><select name="status" class="form-select"><option value="todo" selected>To Do</option><option value="in_progress">In Progress</option><option value="code_review">Code Review</option><option value="qa">QA</option><option value="client_review">Client Review</option><option value="blocked">Blocked</option></select></div></div><div class="modal-footer border-0"><button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><button type="submit" class="btn btn-primary">Add Task</button></div></form></div></div></div>
<?= $this->endSection() ?>
<?= $this->section('scripts') ?>
<script>
const BASE='<?= base_url() ?>'; 
$('#addTaskForm').on('submit',function(e){e.preventDefault();showLoader('Adding...');$.post(`${BASE}admin/tasks/store`,$(this).serialize(),res=>{hideLoader();showToast(res.message,res.status);if(res.status==='success'){bootstrap.Modal.getInstance(document.getElementById('addTaskModal')).hide();setTimeout(()=>location.reload(),500)}},'json')});
let dragged=null; document.querySelectorAll('.kanban-card').forEach(card=>{card.addEventListener('dragstart',()=>{dragged=card;card.classList.add('opacity-50')});card.addEventListener('dragend',()=>{card.classList.remove('opacity-50');dragged=null})}); document.querySelectorAll('.kanban-col').forEach(col=>{col.addEventListener('dragover',e=>{e.preventDefault();if(dragged&&dragged.parentElement!==col)col.appendChild(dragged)});col.addEventListener('drop',e=>{e.preventDefault();if(!dragged)return;const status=col.dataset.status;showLoader('Saving...');$.post(`${BASE}admin/tasks/reorder`,{status:status,ids:Array.from(col.querySelectorAll('.kanban-card')).map(x=>x.dataset.id),csrf_test_name:getCsrfToken()},res=>{hideLoader();showToast(res.message,res.status)},'json')})});
let delId=null;$(document).on('click','.btn-del-task',function(){delId=$(this).data('id');$('#ngConfirmTitle').text($(this).data('confirm-title'));$('#ngConfirmMessage').text($(this).data('confirm'));$('#ngConfirmYes').text($(this).data('confirm-yes'));bootstrap.Modal.getOrCreateInstance(document.getElementById('ngConfirmModal')).show()});$('#ngConfirmYes').off('click').on('click',function(){if(!delId)return;bootstrap.Modal.getInstance(document.getElementById('ngConfirmModal')).hide();showLoader('Deleting...');$.post(`${BASE}admin/tasks/delete/${delId}`,{csrf_test_name:getCsrfToken()},res=>{hideLoader();showToast(res.message,res.status);if(res.status==='success')setTimeout(()=>location.reload(),400)},'json');delId=null});
</script>
<?= $this->endSection() ?>
